[package]
name = "clust_ext"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
clust = { workspace = true }
itertools = { workspace = true }
