[workspace]
resolver = "2"
members = ["packages/oneshot_utils", "packages/oneshot_anthropic_api", "packages/oneshot_cli", "packages/oneshot_common"]

[workspace.package]
version = "0.1.0"
edition = "2021"
rust-version = "1.79.0"
publish = false

[workspace.dependencies]
derive-new = { git = "https://github.com/OmarTawfik-forks/derive-new", branch = "impl-into" } # "0.6.0"
derive_more = { version = "1.0.0-beta.6", features = ["full"] }
fmt-derive = "0.1.2"
derive_builder = "0.13.0"
derive-getters = { git = "https://git.sr.ht/~dengor/derive-getters", branch = "feature/copy-getters-for-primitive-types", features = ["auto_copy_getters"] }
anyhow = "1.0.80"
proptest = "1.5.0"
anthropic-sdk = "0.1.4"
serde_json = "1.0.120"
tokio = { version = "1.38.0", features = ["macros", "fs", "net", "rt"] }
indoc = "2.0.5"
lazy_static = "1.5.0"
strum = { version = "0.26.3", features = ["derive"] }

[profile.test.package.proptest]
opt-level = 3

[profile.test.package.rand_chacha]
opt-level = 3

[profile.dev]
opt-level = 1
