[package]
name = "serialize"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
strum = { workspace = true, optional = true }
serde = { workspace = true }
serde_json = { workspace = true, optional = true }
serde_yaml = { workspace = true, optional = true }
thiserror = { workspace = true }
clap = { optional = true, workspace = true }
derive_more = { workspace = true }
serde-xml-rs = { workspace = true, optional = true }
quick-xml = { workspace = true, optional = true, features = ["serialize"] }
