[package]
name = "oneshot_common"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
derive-new = { workspace = true }
derive_more = { workspace = true }
fmt-derive = { workspace = true }
derive-getters = { workspace = true }
indoc = { workspace = true }
lazy_static = { workspace = true }
strum = { workspace = true }
oneshot_utils = { path = "../oneshot_utils" }
serde = { workspace = true, optional = true }
serde-xml-rs = { workspace = true, optional = true }
