[package]
name = "oneshot_common"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
derive-new = { workspace = true }
derive_more = { workspace = true }
fmt-derive = { workspace = true }
derive-getters = { workspace = true }
indoc = { workspace = true }
strum = { workspace = true }
oneshot_utils = { workspace = true }
serde = { workspace = true }
fs-err = { workspace = true }
bat = { workspace = true }
itertools = { workspace = true }
quick-xml = { workspace = true }
