[package]
name = "oneshot_common"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
indoc = { workspace = true }
lazy_static = { workspace = true }
strum = { workspace = true }
