[package]
name = "oneshot_utils"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
derive-new = { workspace = true }
derive_more = { workspace = true }
fmt-derive = { workspace = true }
derive-getters = { workspace = true }
num-traits = { workspace = true }
fs-err = { workspace = true }
serde = { workspace = true, optional = true }
