[package]
name = "tasks"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
derive_more = { workspace = true }
serde = { workspace = true, optional = true }
derive-getters = { workspace = true }
derive-new = { workspace = true }
