[package]
name = "oneshot_rust_anthropic"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
derive-new = { workspace = true }
derive_more = { workspace = true }
fmt-derive = { workspace = true }
derive-getters = { workspace = true }
oneshot_common = { workspace = true }
oneshot_utils = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true, optional = true }
tokio = { workspace = true }
clap = { workspace = true }
clust = { workspace = true }
clust_ext = { workspace = true }
syn = { workspace = true }
proc-macro2 = { workspace = true, features = ["span-locations"] }
fs-err = { workspace = true }
oneshot_rust = { workspace = true }
strum = { workspace = true }
prettyplease = { workspace = true }
throbber-widgets-tui = { workspace = true }
ratatui = { workspace = true }
tracing-subscriber = { workspace = true }
serde_yaml = { workspace = true }
time = { workspace = true }
save-load = { workspace = true }
constcat = { workspace = true }
directories = { workspace = true }
lazy_static = { workspace = true }
bat = { workspace = true }
quote = { workspace = true }
indexmap = { workspace = true }
rustc-hash = { workspace = true }
tempfile = { workspace = true }
lsp-types = { workspace = true }

[package.metadata.cargo-machete]
ignored = ["proc_macro2"]
