[package]
name = "oneshot_rust_anthropic"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
derive-new = { workspace = true }
derive_more = { workspace = true }
fmt-derive = { workspace = true }
derive-getters = { workspace = true }
oneshot_common = { path = "../oneshot_common", features = ["serde", "serde-xml-rs"] }
oneshot_utils = { path = "../oneshot_utils" }
anyhow = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
clap = { workspace = true }
clust = { workspace = true }
clust_ext = { path = "../clust_ext" }
syn = { workspace = true }
env_logger = { workspace = true }
tokio-stream = { workspace = true }
