[package]
name = "oneshot_rust_anthropic"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
derive-new = { workspace = true }
derive_more = { workspace = true }
fmt-derive = { workspace = true }
derive-getters = { workspace = true }
oneshot_common = { workspace = true }
oneshot_utils = { workspace = true }
anyhow = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
clap = { workspace = true }
clust = { workspace = true }
clust_ext = { path = "../clust_ext" }
syn = { workspace = true }
env_logger = { workspace = true }
tokio-stream = { workspace = true }
fs-err = { workspace = true }
oneshot_rust = { path = "../oneshot_rust" }
strum = { workspace = true }
prettyplease = { workspace = true }
throbber-widgets-tui = { workspace = true }
ratatui = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
serde_yaml = { workspace = true }
time = { workspace = true }
serialize = { path = "../serialize", features = ["clap", "serde_json", "serde_yaml"] }
constcat = { workspace = true }
directories = { workspace = true }
lazy_static = { workspace = true }
tap = { workspace = true }
bat = { workspace = true }
fierce_nerds_node = { path = "../../../zenbox/fierce_nerds_node" }
quote = { workspace = true }
indexmap = { workspace = true }
rustc-hash = { workspace = true }
tempfile = { workspace = true }
