[package]
name = "oneshot_rust"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
derive-new = { workspace = true }
derive_more = { workspace = true }
fmt-derive = { workspace = true }
derive-getters = { workspace = true }
syn = { workspace = true }
quote = { workspace = true }
serde = { workspace = true, optional = true }
oneshot_utils = { workspace = true }
oneshot_common = { workspace = true }
bat = { workspace = true }
pulldown-cmark = { workspace = true }
serde_json = { workspace = true }
duct = { workspace = true }
indexmap = { workspace = true }
