[package]
name = "oneshot_rust"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
derive-new = { workspace = true }
derive_more = { workspace = true }
fmt-derive = { workspace = true }
derive-getters = { workspace = true }
syn = { workspace = true, features = ["full"] }
quote = { workspace = true }
oneshot_utils = { path = "../oneshot_utils" }
serde = { workspace = true, optional = true }
oneshot_common = { path = "../oneshot_common" }
